import type {AppProps} from 'next/app';
import {createGlobalStyle, ThemeProvider} from 'styled-components';
import Layout from "../components/Layout";
import Head from "next/head";
import React from "react";
import theme, {ThemeType} from "../styles/theme";

declare module 'styled-components' {
  export interface DefaultTheme extends ThemeType {
  }
}

const GlobalStyle = createGlobalStyle`

  @font-face {
    font-family: 'Cubano';
    src: url('/fonts/Cubano.ttf') format('TrueType');
  }  
  
  @font-face {
    font-family: 'Filson Soft';
    src: url('/fonts/Filson_Soft.ttf') format('TrueType');
  }

  html,
  body {
    padding: 0;
    margin: 0;
    font-family: ${({theme}) => theme.fonts.filson};
  }

  a {
    color: inherit;
    text-decoration: none;
  }

  * {
    box-sizing: border-box;
  }

  @media (prefers-color-scheme: dark) {
    html {
      color-scheme: dark;
    }

    body {
      color: white;
      background: black;
    }
  }

`;

function MyApp({Component, pageProps}: AppProps) {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <ThemeProvider theme={theme}>
      <GlobalStyle/>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </ThemeProvider>
  </>;
}

export default MyApp;
